# name: CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
#   workflow_dispatch:    # manual trigger bhi chahiye toh

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v4

#       - name: Use Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 18

#       - name: Cache node modules
#         uses: actions/cache@v4
#         with:
#           path: ~/.npm
#           key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#           restore-keys: |
#             ${{ runner.os }}-node-

#       - name: Install dependencies
#         run: npm ci

#       # agar tumne tests configure kiye hain vitest/jest se tab run karo
#       # warna is step ko hata bhi sakte ho
#       - name: Run tests
#         run: npm test || echo "No tests configured"

#       - name: Build project
#         run: npm run build

#       - name: Upload build artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: dist
#           path: ./dist

name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # jab bhi main branch pe push hoga
  workflow_dispatch: # manual trigger bhi chahiye toh

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # vite build output

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
